### PR TITLE
Add support for custom Xen Orchestra repository

### PR DESCRIPTION
**Pull request by jereksel**
Hi,

I really like this script, but I'm using custom Xen Orchestra repository that removes premium features from sidebar. I though that adding option to set custom Xen Orchestra repository would be good idea.

### CODE REVIEW

**Comment by ronivay** [comment]
Good stuff, thanks

**Comment by olivierlambert** [comment]
Hi there,

Can you please take time to read this? https://xen-orchestra.com/docs/installation.html#banner-and-warnings

**Comment by ronivay** [comment]
> Hi there,
> 
> Can you please take time to read this? https://xen-orchestra.com/docs/installation.html#banner-and-warnings

I assume this wasn't really intended for me but as a maintainer of this said script i'll answer from my part. As you may have seen from README i encourage everyone with serious use case to look towards XOA and supported version of xen orchestra. I also have a very strict policy not to edit any of the source code with this script which is pulled from your git repository. Goal is to make your own "from sources" procedure automatic and easy for new users which want to experience xen orchestra. 

Since we are working with open source, i don't mind allowing a use of custom code base if they want to do so.

**Comment by olivierlambert** [comment]
It wasn't specially toward you @ronivay :wink: 

I'm just explaining to people who want to remove some stuff to do that in a "friendly" manner as possible, because those 2 projects aren't coming out of thin air, but require a lot of time and money.

I'm completely OK if people do their modification locally for their own use case. But in case someone do that at a "larger scale", it's clearly more problematic for us. So it was really just a friendly reminder, nothing else :smile:

**Pull request merged**
