### PR TITLE
Update xo-install.sh

### PR DESCRIPTION
**Pull request by dabbill**
cp to wrong directory

### CODE REVIEW

**Comment by ronivay** [comment]
Hi,

Can you give a little bit more information how this goes wrong for you. I can't see or reproduce any difference.

**Comment by dabbill** [comment]
Hello,
When I was trying to run the script on a fresh CentOS 7 install it would
create a subfolder xen-orchestra in the date appended folder. This was
causing GIT to bomb out saying there was no ".git" folder. Once I added the
"/." to the end of the cp command git would not bomb out.

**Comment by ronivay** [comment]
Hi,

Thanks!

My tests revealed that indeed new installations failed, but this was because $INSTALLDIR/xo-builds directory didn't exist. This prevented cp to copy $XO_SRC folder as xo-builds/xen-orchestra-$TIME.

I commited a fix (https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/f588105e06bc794d16bb90a242dfe5f1bdfeb7da) which creates missing xo-builds folder if it doesn't exist and a build for fresh CentOS 7 box worked fine.

**Comment by dabbill** [comment]
Okay awesome!
I only spent a few minutes going through the script.  :-)

-----Original Message-----

**Pull request closed without merging**
