### PR TITLE
Added NFS to CentOS install

### PR DESCRIPTION
**Pull request by penetal**
Allows for backup to NFS remotes.

### CODE REVIEW

**Comment by ronivay** [comment]
Hi,

Thanks. This made me check the packages and i noticed that ubuntu/debian installation has been missing an important package for file level restore operations. Fixed that along with nfs-utils/nfs-common packages in commit: https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/1765375cb875dedcce584817b1b66db3750b643b

**Comment by penetal** [comment]
Do you know if there is any way to get vhdi-tools on CentOS? Would love to have file level restore without having to get a single VM that is different than the rest of our environment.

**Comment by ronivay** [comment]
Yeah i just started to reserach this. cert.org forensics repository seems to have a package for this. Propably the best option currently.

https://centos.pkgs.org/7/forensics-x86_64/libvhdi-tools-20160108-1.el7.x86_64.rpm.html

**Comment by penetal** [comment]
Thanks for the tip, I tried it out now and I could choose from the boot partition however the LVM volume (aka /) was a bigger issue. I will let you know if I find out why when I have some more time.

Used a fresh CentOS 7.5 VM for XO using your script.

```
Command failed: vgchange -ay cl_centos7template 
File descriptor 11 (/var/lib/xo-server/data/leveldb/LOG) leaked on vgchange invocation. Parent PID 13118: node 
File descriptor 13 (/var/lib/xo-server/data/leveldb/LOCK) leaked on vgchange invocation. Parent PID 13118: node 
File descriptor 15 (/var/lib/xo-server/data/leveldb/000003.log) leaked on vgchange invocation. Parent PID 13118: node 
File descriptor 20 (/var/lib/xo-server/data/leveldb/MANIFEST-000002) leaked on vgchange invocation. Parent PID 13118: node   
Volume group "cl_centos7template" not found   Cannot process volume group cl_centos7template

```

**Pull request closed without merging**
